import { Bike2,Bike3,Bike4,Bike5,Bike6,Bike7,Bike8,Bike9,Bike10,Blog,Event, Service,Blog1,Blog2,Blog3,Blog4,Blog5,Blog6,Blog7,Blog8,Blog9,Blog10,Blog11} from "../assets/images/index";
import {Gear, Brake, Outlet, Rider,Renagade, BridgeSport,Crpto,Smash,power_pond,Ready,control,Grid,Brain,Comp,Hd,phenom,Carbon,Team,Black,ClipShoes,Drybag,Gray,Helmet,RedHelmet,shortShirt,Sigma,SWorkShoes,Tracker} from '../assets/images/index';


export const Arival_Feature=[
    {
        id:1,
        text:'Riprock 24-Gloss Blaze Orange/Smoke',
        imgURL:Bike2,
        from:'Guff',
            price:'700.00',
            btn:'New',
          detail_information: {
          brake: 'Vorne: Shimano BR-RX400, 2-Kolben, Hydraulische Scheibenbremse / Hinten: Shimano BR-RX400, 2-Kolben, Hydraulische Scheibenbremse',
          fork: 'Felt Gravel, UHC Performance carbon fiber with aluminum steerer tube',
          color: 'Brown and gold',
          rearTyre: 'Maxxis Refuse, 700x40 mm',
          cassette: 'Shimano CS-HG700, 11-34 T',
          crankset: 'Shimano GRX, FC-RX600, 46/30 T',
          wheelSize: '28',
          wheelSheet: 'Devox WheelRDS.A1, Tubeless ready, Center Lock, 12x100/12x142 mm',
          handlebar: 'Devox DBar.A2 GXA 31,8 mm, 440 mm',
          modelYear: '2022',
          frame: 'Felt BROAM, SuperLite aluminum',
          frameSize: 'M',
          saddle: 'Selle Royal Essenza Gel',
          shifter: 'Shimano GRX, ST-RX600',
          rearDerailleur: 'Shimano GRX, RD-RX810, 22-S',
          frontDerailleur: 'Shimano GRX, FD-RX810',
          stem: 'Devox StemR.A2',
        }
    },
    {
        id:2,
        text:'Sirrux X5.0-Satin Red Tint/Black/Gray',
        imgURL:Bike3,
        from:'Enduro',
        before:'$8,700.00USD',
        price:'2250.00',
        btn:'New',
               detail_information: {
          brake: 'Vorne: Shimano BR-RX400, 2-Kolben, Hydraulische Scheibenbremse / Hinten: Shimano BR-RX400, 2-Kolben, Hydraulische Scheibenbremse',
          fork: 'Felt Gravel, UHC Performance carbon fiber with aluminum steerer tube',
          color: 'Brown and gold',
          rearTyre: 'Maxxis Refuse, 700x40 mm',
          cassette: 'Shimano CS-HG700, 11-34 T',
          crankset: 'Shimano GRX, FC-RX600, 46/30 T',
          wheelSize: '28',
          wheelSheet: 'Devox WheelRDS.A1, Tubeless ready, Center Lock, 12x100/12x142 mm',
          handlebar: 'Devox DBar.A2 GXA 31,8 mm, 440 mm',
          modelYear: '2022',
          frame: 'Felt BROAM, SuperLite aluminum',
          frameSize: 'M',
          saddle: 'Selle Royal Essenza Gel',
          shifter: 'Shimano GRX, ST-RX600',
          rearDerailleur: 'Shimano GRX, RD-RX810, 22-S',
          frontDerailleur: 'Shimano GRX, FD-RX810',
          stem: 'Devox StemR.A2',
        }

    },
      {
        id:3,
        text:'Turbo Combo-Sl 5.0 -Smoke/Transparent',
        imgURL:Bike4,
        from:'Diamond',
        before:'$21,199.00USD',
        price:'2349.00',
        btn:'New',
        salebtn:'Sale',
              detail_information: {
          brake: 'Vorne: Shimano BR-RX400, 2-Kolben, Hydraulische Scheibenbremse / Hinten: Shimano BR-RX400, 2-Kolben, Hydraulische Scheibenbremse',
          fork: 'Felt Gravel, UHC Performance carbon fiber with aluminum steerer tube',
          color: 'Brown and gold',
          rearTyre: 'Maxxis Refuse, 700x40 mm',
          cassette: 'Shimano CS-HG700, 11-34 T',
          crankset: 'Shimano GRX, FC-RX600, 46/30 T',
          wheelSize: '28',
          wheelSheet: 'Devox WheelRDS.A1, Tubeless ready, Center Lock, 12x100/12x142 mm',
          handlebar: 'Devox DBar.A2 GXA 31,8 mm, 440 mm',
          modelYear: '2022',
          frame: 'Felt BROAM, SuperLite aluminum',
          frameSize: 'M',
          saddle: 'Selle Royal Essenza Gel',
          shifter: 'Shimano GRX, ST-RX600',
          rearDerailleur: 'Shimano GRX, RD-RX810, 22-S',
          frontDerailleur: 'Shimano GRX, FD-RX810',
          stem: 'Devox StemR.A2',
        }

    },
      {
        id:4,
        text:'Stumpjumper 15Pro -Satin Green/Gunmental',
        imgURL:Bike5,
        from:'Extreme',
        price:'6000.00',
        btn:'New',
            detail_information: {
          brake: 'Vorne: Shimano BR-RX400, 2-Kolben, Hydraulische Scheibenbremse / Hinten: Shimano BR-RX400, 2-Kolben, Hydraulische Scheibenbremse',
          fork: 'Felt Gravel, UHC Performance carbon fiber with aluminum steerer tube',
          color: 'Brown and gold',
          rearTyre: 'Maxxis Refuse, 700x40 mm',
          cassette: 'Shimano CS-HG700, 11-34 T',
          crankset: 'Shimano GRX, FC-RX600, 46/30 T',
          wheelSize: '28',
          wheelSheet: 'Devox WheelRDS.A1, Tubeless ready, Center Lock, 12x100/12x142 mm',
          handlebar: 'Devox DBar.A2 GXA 31,8 mm, 440 mm',
          modelYear: '2022',
          frame: 'Felt BROAM, SuperLite aluminum',
          frameSize: 'M',
          saddle: 'Selle Royal Essenza Gel',
          shifter: 'Shimano GRX, ST-RX600',
          rearDerailleur: 'Shimano GRX, RD-RX810, 22-S',
          frontDerailleur: 'Shimano GRX, FD-RX810',
          stem: 'Devox StemR.A2',
        }

    },
      {
        id:5,
        text:'Turbo Combo 4.0 IGH -Cast Black',
        imgURL:Bike6,
        from:'Obus',
        price:'3849.00',
        btn:'New',
              detail_information: {
          brake: 'Vorne: Shimano BR-RX400, 2-Kolben, Hydraulische Scheibenbremse / Hinten: Shimano BR-RX400, 2-Kolben, Hydraulische Scheibenbremse',
          fork: 'Felt Gravel, UHC Performance carbon fiber with aluminum steerer tube',
          color: 'Brown and gold',
          rearTyre: 'Maxxis Refuse, 700x40 mm',
          cassette: 'Shimano CS-HG700, 11-34 T',
          crankset: 'Shimano GRX, FC-RX600, 46/30 T',
          wheelSize: '28',
          wheelSheet: 'Devox WheelRDS.A1, Tubeless ready, Center Lock, 12x100/12x142 mm',
          handlebar: 'Devox DBar.A2 GXA 31,8 mm, 440 mm',
          modelYear: '2022',
          frame: 'Felt BROAM, SuperLite aluminum',
          frameSize: 'M',
          saddle: 'Selle Royal Essenza Gel',
          shifter: 'Shimano GRX, ST-RX600',
          rearDerailleur: 'Shimano GRX, RD-RX810, 22-S',
          frontDerailleur: 'Shimano GRX, FD-RX810',
          stem: 'Devox StemR.A2',
        }

    },
      {
        id:6,
        text:'Roubaix SL8 Pro -Gloss Metalic Pine',
        imgURL:Bike7,
        from:'Diamond',
        price:'8500.00',
        btn:'New',
         detail_information: {
          brake: 'Vorne: Shimano BR-RX400, 2-Kolben, Hydraulische Scheibenbremse / Hinten: Shimano BR-RX400, 2-Kolben, Hydraulische Scheibenbremse',
          fork: 'Felt Gravel, UHC Performance carbon fiber with aluminum steerer tube',
          color: 'Brown and gold',
          rearTyre: 'Maxxis Refuse, 700x40 mm',
          cassette: 'Shimano CS-HG700, 11-34 T',
          crankset: 'Shimano GRX, FC-RX600, 46/30 T',
          wheelSize: '28',
          wheelSheet: 'Devox WheelRDS.A1, Tubeless ready, Center Lock, 12x100/12x142 mm',
          handlebar: 'Devox DBar.A2 GXA 31,8 mm, 440 mm',
          modelYear: '2022',
          frame: 'Felt BROAM, SuperLite aluminum',
          frameSize: 'M',
          saddle: 'Selle Royal Essenza Gel',
          shifter: 'Shimano GRX, ST-RX600',
          rearDerailleur: 'Shimano GRX, RD-RX810, 22-S',
          frontDerailleur: 'Shimano GRX, FD-RX810',
          stem: 'Devox StemR.A2',
        }

    },
      {
        id:7,
        text:'Roll 3.0 Low Entry',
        imgURL:Bike8,
        from:'Guff',
        price:'1199.00',
        btn:'New',
        detail_information: {
          brake: 'Vorne: Shimano BR-RX400, 2-Kolben, Hydraulische Scheibenbremse / Hinten: Shimano BR-RX400, 2-Kolben, Hydraulische Scheibenbremse',
          fork: 'Felt Gravel, UHC Performance carbon fiber with aluminum steerer tube',
          color: 'Brown and gold',
          rearTyre: 'Maxxis Refuse, 700x40 mm',
          cassette: 'Shimano CS-HG700, 11-34 T',
          crankset: 'Shimano GRX, FC-RX600, 46/30 T',
          wheelSize: '28',
          wheelSheet: 'Devox WheelRDS.A1, Tubeless ready, Center Lock, 12x100/12x142 mm',
          handlebar: 'Devox DBar.A2 GXA 31,8 mm, 440 mm',
          modelYear: '2022',
          frame: 'Felt BROAM, SuperLite aluminum',
          frameSize: 'M',
          saddle: 'Selle Royal Essenza Gel',
          shifter: 'Shimano GRX, ST-RX600',
          rearDerailleur: 'Shimano GRX, RD-RX810, 22-S',
          frontDerailleur: 'Shimano GRX, FD-RX810',
          stem: 'Devox StemR.A2',
        }

    },
     {
        id:8,
        text:'Termac SL7 Comp -Gloss Metalic Spruce',
        imgURL:Bike9,
        from:'Obus',
        price:'4700.00',
        btn:'New',
        salebtn:'Sale',
           detail_information: {
          brake: 'Vorne: Shimano BR-RX400, 2-Kolben, Hydraulische Scheibenbremse / Hinten: Shimano BR-RX400, 2-Kolben, Hydraulische Scheibenbremse',
          fork: 'Felt Gravel, UHC Performance carbon fiber with aluminum steerer tube',
          color: 'Brown and gold',
          rearTyre: 'Maxxis Refuse, 700x40 mm',
          cassette: 'Shimano CS-HG700, 11-34 T',
          crankset: 'Shimano GRX, FC-RX600, 46/30 T',
          wheelSize: '28',
          wheelSheet: 'Devox WheelRDS.A1, Tubeless ready, Center Lock, 12x100/12x142 mm',
          handlebar: 'Devox DBar.A2 GXA 31,8 mm, 440 mm',
          modelYear: '2022',
          frame: 'Felt BROAM, SuperLite aluminum',
          frameSize: 'M',
          saddle: 'Selle Royal Essenza Gel',
          shifter: 'Shimano GRX, ST-RX600',
          rearDerailleur: 'Shimano GRX, RD-RX810, 22-S',
          frontDerailleur: 'Shimano GRX, FD-RX810',
          stem: 'Devox StemR.A2',
        }
        
    },
     {
        id:9,
        text:'Crux Expert -Gloss Carbon/Tarmac Black',
        imgURL:Bike10,
        from:'Steel',
        price:'4299.00',
        btn:'New',
        salebtn:'Sale',
        detail_information: {
          brake: 'Vorne: Shimano BR-RX400, 2-Kolben, Hydraulische Scheibenbremse / Hinten: Shimano BR-RX400, 2-Kolben, Hydraulische Scheibenbremse',
          fork: 'Felt Gravel, UHC Performance carbon fiber with aluminum steerer tube',
          color: 'Brown and gold',
          rearTyre: 'Maxxis Refuse, 700x40 mm',
          cassette: 'Shimano CS-HG700, 11-34 T',
          crankset: 'Shimano GRX, FC-RX600, 46/30 T',
          wheelSize: '28',
          wheelSheet: 'Devox WheelRDS.A1, Tubeless ready, Center Lock, 12x100/12x142 mm',
          handlebar: 'Devox DBar.A2 GXA 31,8 mm, 440 mm',
          modelYear: '2022',
          frame: 'Felt BROAM, SuperLite aluminum',
          frameSize: 'M',
          saddle: 'Selle Royal Essenza Gel',
          shifter: 'Shimano GRX, ST-RX600',
          rearDerailleur: 'Shimano GRX, RD-RX810, 22-S',
          frontDerailleur: 'Shimano GRX, FD-RX810',
          stem: 'Devox StemR.A2',
        }

    },
    {
      id:10,
      text:'S-Work Renagade Realt T5/T7',
      imgURL:Renagade,
      from:'Obus',
      price:'80.00',
      btn:'New',
        detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        }
    },
    {
      id:11,
      text:'Bridge  Sport',
      imgURL:BridgeSport,
      from:'Guff',
      price:'70.00',
      btn:'New',
       detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        }
    },
    {
      id:12,
      text:'Supacaz Krypto Pedal-Black',
      imgURL:Crpto,
      from:'Hard Metal',
      price:'150.00',
      btn:'New',
       detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        }
    },
    {
      id:13,
      text:'Pedal-Thermopoly',
      imgURL:Smash,
      from:'Hard Metal',
      price:'56.00',
      btn:'New',
       detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        }
    },
    {
      id:14,
      text:'Power Comp',
      imgURL:power_pond,
      from:'Lizard',
      price:'150.00',
      btn:'New',
       detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        }
    },
    {
      id:15,
      text:'S-Work Pathfinder 2Bliss Ready',
      imgURL:Ready,
      from:'Obus',
      price:'80.00',
      btn:'New',
       detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        }
    },
    {
      id:16,
      text:'Rocal Control SL Team',
      imgURL:control,
      from:'Rhomb',
      price:'125.00',
      btn:'New',
       detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        }
    },
    {
      id:17,
      text:'Butcher Grid Trail 2Bliss Ready T7',
      imgURL:Grid,
      from:'Enduro',
      price:'80.00',
      btn:'New',
       detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        }
    },
    {
      id:18,
      text:'RockShox SID SL Ultimate Brain',
      imgURL:Brain,
      from:'Extreme',
      price:'950.00',
      btn:'New',
       detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        }
    },
    {
      id:19,
      text:'Future Stem Comp',
      imgURL:Comp,
      from:'Obus',
      price:'60.00',
      btn:'New',
       detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        }
    },
   
    {
      id:21,
      text:'S-Works Phenon with Morror',
      imgURL:phenom,
      from:'Diamond',
      price:'450.00',
      btn:'New',
       detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        }
    },
    {
      id:22,
      text:'Stumpjumper Carbon 27.5 Suspension Link',
      imgURL:Carbon,
      from:'Steel',
      price:'79.00',
      btn:'New',
       detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        }
    },
    {
      id:23,
      text:'Rapcide CLX II Team',
      imgURL:Team,
      from:'Rhomb',
      price:'79.00',
      btn:'New',
       detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        },
        // Black,ClipShoes,Drybag,Gray,Helmet,RedHelmet,shortShirt,Sigma,SWorkShoes,Tracker
    },
    
     {
          id:24,
          text:'S-Works Recon Shoe-Black',
          imgURL:ClipShoes,  
          from:'Hard Metal',
          price:'499.00',
          btn:'New',
             detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        },
        },
        {
          id:25,
          text:'Abus X Canyon Cycling Helmet-Black',
          imgURL:Helmet,  
          from:'Rhomb',
          price:'294.00',
          btn:'New',
             detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        },
        },
         {
          id:26,
          text:'Abus X Canyon Cycling Helmet-Red',
          imgURL:RedHelmet,  
          from:'Rhomb',
          price:'294.00',
          btn:'New',
             detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        },
        },
         {
          id:27,
          text:'Canyons Men Classic Cycling Jersey ',
          imgURL:shortShirt,  
          from:'Guff',
          price:'69.00',
          btn:'New',
             detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        },
        },
             {
          id:28,
          text:'Computer ',
          imgURL:Tracker,  
          from:'Hard Metal',
          price:'279.95',
          btn:'New',   detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        },
        },
          {
          id:29,
          text:'S-Works Torch Lace-Black ',
          imgURL:Sigma,  
          from:'Guff',
          price:'350.00',
          btn:'New',
             detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        },
        },
         {
          id:30,
          text:'S-Works Recon Shoe-Black ',
          imgURL:SWorkShoes,  
          from:'Hard Metal',
          price:'499.00',
          btn:'New',
             detail_information: {
          brake:'Lorem ipsum dolor sit amet',
          fork:'Aliquam et libero quis orci ullamcorper pretium',
          color:'Fusce vehicula dui et',
          rearTyre:'Maecenas ultrices aliquam sapien sit amet blandit',
          cassette:'Vestibulum nec neque vestibulum, iaculis libero sit amet, tincidunt nibh',
          crankset:'Praesent vitae euismod diam',
        },
        },
    
    
].map((item)=>(
  {
    ...item,
    addToCart:'Detail'

  }
));


export const Explores=[
  {
    imgURl:Rider,
    text:'BIKES',
  },
  {
    imgURl:Brake,
    text:'PARTS',
  },
  {
    imgURl:Gear,
    text:'GEAR',
  },
  {
    imgURl:Outlet,
    text:'OUTLET',
  }
];

export const Explore2=[
  {
    imgURl:Service,
    text:'BIKES',
  },
  {
    imgURl:Blog,
    text:'BLOG',
  },
  {
    imgURl:Event,
    text:'EVENTS',
  }
];
 export const Blog_Feature=[
  {
    id:1,
    text:"Tips & Trick",
    imgURL:Blog1,
    date:"Jun 19 2024",
    tittle:'Start mountain biking in 6 steps',
  },
  {
    id:2,
    text:"Routes",
    imgURL:Blog2,
    date:"May 16 2024",
    tittle:'The Charm of riding through Switzerland',
  },
  {
    id:3,
    text:"Reviews",
    imgURL:Blog3,
    date:"May 7 2024",
    tittle:'Review: Specialized S-Work Tarmak SL8',
  },
  {
    id:4,
    text:"News",
    imgURL:Blog4,
    date:"Apr 18 2024",
    tittle:'Verbia is about to become the mecca of cycling',
  },
  {
    id:5,
    text:"Bike 101",
    imgURL:Blog5,
    date:"Apr 9 2024",
    tittle:'City Bike vs Road Bike:',
  },
  {
    id:6,
    text:"News",
    imgURL:Blog6,
    date:"Ma4 22 2024",
    tittle:'Tour De Frence 2024',
  },
  {
    id:7,
    text:"Bike 101",
    imgURL:Blog7,
    date:"Mar 4 2024",
    tittle:'Understanding Track cycling events',
  },
  {
    id:8,
    text:"Bike 101",
    imgURL:Blog8,
    date:"Feb 28 2024",
    tittle:'Gravel bike vs Hardtail bike',
  },
  {
    id:9,
    text:"Routes",
    imgURL:Blog9,
    date:"Feb 20 2024",
    tittle:'5 Stunning cycling routes in Lugano',
  },
  {
    id:10,
    text:"Tips and Advices",
    imgURL:Blog10,
    date:"Feb 5 2024",
    tittle:'E-MTB buying Guide',
  },
 
 ]